[project]
name = "engenharia-dados-azure-databricks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "ruff>=0.7.3",
]
